<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamMemberSeeder extends Seeder
{
    public function run(): void
    {
        $teamMembers = [
            // Principal
            [
                'department_id' => null,
                'role_id' => 1,
                'section_assigned' => null,
                'email' => 'principal@teresco.edu.gh',
                'name' => 'Mr. David M. Kariuki',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => 'Dedicated to excellence and leadership in education, inspiring students and staff alike.',
                'is_hod' => false,
                'phone' => '+254758660300',
            ],
            // Deputy Principals
            [
                'department_id' => null,
                'role_id' => 2,
                'section_assigned' => 'Administration',
                'email' => 'deputy.admin@teresco.edu.gh',
                'name' => 'Joshua Mwangi',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => 'Supporting our institution\'s vision and daily operations',
                'is_hod' => false,
                'phone' => '+254758660301',
            ],
            [
                'department_id' => null,
                'role_id' => 2,
                'section_assigned' => 'Academics',
                'email' => 'deputy.academics@teresco.edu.gh',
                'name' => 'Lydia Ndirangu',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => 'Supporting our institution\'s vision and daily operations',
                'is_hod' => false,
                'phone' => '+254758660302',
            ],
            // HODs - Academic Departments (8 departments)
            [
                'department_id' => 1, // Cosmetology
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.cosmetology@teresco.edu.gh',
                'name' => 'Jacob Nyaga',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660303',
            ],
            [
                'department_id' => 2, // Hospitality
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.hospitality@teresco.edu.gh',
                'name' => 'Lily Mugo',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660304',
            ],
            [
                'department_id' => 3, // Fashion and Textile
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.fashion@teresco.edu.gh',
                'name' => 'Madam Jane',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660305',
            ],
            [
                'department_id' => 4, // Building and Civil
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.building@teresco.edu.gh',
                'name' => 'Gideon Muraguri',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660306',
            ],
            [
                'department_id' => 5, // Electrical
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.electrical@teresco.edu.gh',
                'name' => 'Mr. Josiah',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660307',
            ],
            [
                'department_id' => 6, // ICT
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.ict@teresco.edu.gh',
                'name' => 'Ascar Jebet',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660308',
            ],
            [
                'department_id' => 7, // Agriculture
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.agriculture@teresco.edu.gh',
                'name' => 'Anthony S.',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660309',
            ],
            [
                'department_id' => 8, // Mechanical
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.mechanical@teresco.edu.gh',
                'name' => 'Mugure Ngigi',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660310',
            ],

            // Non-Academic HODs
            [
                'department_id' => 9, // Finance
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.finance@teresco.edu.gh',
                'name' => 'Mr. John Doe',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660317',
            ],
            [
                'department_id' => 10, // Student Affairs
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.studentaffairs@teresco.edu.gh',
                'name' => 'Mr. Jane Smith',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660318',
            ],
            [
                'department_id' => 11, // Procurement
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.procurement@teresco.edu.gh',
                'name' => 'Mr. Robert Brown',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660319',
            ],
            [
                'department_id' => 12, // Library
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.library@teresco.edu.gh',
                'name' => 'Mr. Michael Johnson',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660320',
            ],
            // Additional Non-Academic HODs
            [
                'department_id' => 13, // Guiding & Counselling
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.counselling@teresco.edu.gh',
                'name' => 'Mrs. Grace Wanjiku',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660321',
            ],
            [
                'department_id' => 14, // Industrial Liaison Office (IILO)
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.iilo@teresco.edu.gh',
                'name' => 'Mr. Peter Kamau',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660322',
            ],
            [
                'department_id' => 15, // Sports
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.sports@teresco.edu.gh',
                'name' => 'Mr. James Ochieng',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660323',
            ],
            [
                'department_id' => 16, // Music and Arts
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.musicarts@teresco.edu.gh',
                'name' => 'Madam Sarah Njoroge',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660324',
            ],

            // Trainers
            [
                'department_id' => 4, // Building and Civil
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'felix@teresco.edu.gh',
                'name' => 'Felix Njeru',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660311',
            ],
            [
                'department_id' => 4,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'festus@teresco.edu.gh',
                'name' => 'Festus Chesaro',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660312',
            ],
            [
                'department_id' => 4,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'alphonse@teresco.edu.gh',
                'name' => 'Alphonse Otieno',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660313',
            ],
            [
                'department_id' => 2, // Hospitality
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'lucy@teresco.edu.gh',
                'name' => 'Madam Lucy O.',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660314',
            ],
            [
                'department_id' => 4,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'njeri@teresco.edu.gh',
                'name' => 'Madam Njeri',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660315',
            ],
            [
                'department_id' => 3, // Fashion and Textile
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'faithfashion@teresco.edu.gh',
                'name' => 'Madam Faith',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660316',
            ],
            [
                'department_id' => 1, // Cosmetology
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'peninah@teresco.edu.gh',
                'name' => 'Madam Peninah',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660401',
            ],
            [
                'department_id' => 6, // ICT
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'lawrence@teresco.edu.gh',
                'name' => 'Lawrence Mwaniki',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660402',
            ],
            [
                'department_id' => 6,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'titus@teresco.edu.gh',
                'name' => 'Titus Tum',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660403',
            ],
            [
                'department_id' => 8, // Mechanical
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'evans@teresco.edu.gh',
                'name' => 'Evans Odima',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660404',
            ],
            [
                'department_id' => 6,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'june@teresco.edu.gh',
                'name' => 'June Njagi',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660405',
            ],
            [
                'department_id' => 2,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'mercy@teresco.edu.gh',
                'name' => 'Madam Mercy',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660406',
            ],
            [
                'department_id' => 2,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'kioko@teresco.edu.gh',
                'name' => 'Mr. Kioko',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660407',
            ],
            [
                'department_id' => 4,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'dennis@teresco.edu.gh',
                'name' => 'Mr. Dennis',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660408',
            ],
            [
                'department_id' => 3,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'kimathi@teresco.edu.gh',
                'name' => 'Kimathi Mwiti',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660409',
            ],
            [
                'department_id' => 4,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'aminga@teresco.edu.gh',
                'name' => "Mr. Aming'a",
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660410',
            ],
            [
                'department_id' => 6,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'graceni@teresco.edu.gh',
                'name' => 'Madam Grace N.',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660411',
            ],
            [
                'department_id' => 6,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'bilhah@teresco.edu.gh',
                'name' => 'Madam Bilhah',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660412',
            ],
            [
                'department_id' => 6,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'ambrose@teresco.edu.gh',
                'name' => 'Mr. Ambrose',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660413',
            ],
            [
                'department_id' => 8,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'thomas@teresco.edu.gh',
                'name' => 'Mr. Thomas',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660414',
            ],
            [
                'department_id' => 2,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'evelynne@teresco.edu.gh',
                'name' => 'Evelynne Donga',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660415',
            ],
            [
                'department_id' => 1,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'fernice@teresco.edu.gh',
                'name' => 'Fernice Gichevu',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660416',
            ],
            [
                'department_id' => 1,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'monica@teresco.edu.gh',
                'name' => 'Madam Monica',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660417',
            ],
            [
                'department_id' => 5, // Electrical
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'okacha@teresco.edu.gh',
                'name' => 'Mr. Okacha',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660418',
            ],
        ];

        foreach ($teamMembers as $member) {
            DB::table('team_members')->insert($member);
        }
    }
}
